### ISSUE TITLE
Euler Method no good for planetary problems

### ISSUE THREAD

**Issue by paulnakroshis** [JoshuaSimon/N-Body-Problem#1]
I would omit the Euler method from your code, as it does not conserve energy. 
Check it and see---the energy will grow without limit as t increases. The Euler-Cromer
will fare better, and of course RK4 even better still. 

Best,
-p

**Comment by SV-97** [comment]
> I would omit the Euler method from your code, as it does not conserve energy.
> Check it and see---the energy will grow without limit as t increases. The Euler-Cromer
> will fare better, and of course RK4 even better still.
> 
> Best,
> -p

Hey, thanks for your comment! Sorry for taking a while to answer. We originally started this as basically a survey of different numerical ODE-integrator algorithms, so the bad performance of the Euler-method here may be understood more as a feature rather than a bug ;) I just pushed a more "modern" implementation that solves the general d-dimensional n-body problem using the DOPRI 5(4) algorithm.

**Comment by JoshuaSimon** [comment]
Closed because of inactivity. @SV-97 delivered a nice solution and did some great refactoring of the python version.
